; псевдо структура всей этой мутной темки3
; colon "<key>", <metka> 
; db "<value>", 0

colon "leha", leha
db "love nissan", 0

colon "evgen", evgen
db "love chayhana", 0

colon "kiruha", kiruha
db "love ushu", 0

colon "kostyan", kostyan
db "love chetkie pedali", 0

colon "victor", victor
db "search kanarayka", 0

colon "maks", maks
db "like dota and scanf"

colon "ilya", ilya
db "wrestler kronbars", 0

